import "../styles/globals.css";
import Head from "next/head";
import { AuthProvider } from "../context/AuthContext";
import { useRouter } from "next/router";
import Protected from "../components/Protected";
import "react-toastify/dist/ReactToastify.css";
import "../styles/Loader.scss";
function MyApp({ Component, pageProps }) {
  const noAuth = ["/login", "/register", "/", "/shop"];
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />

      </Head>

      <AuthProvider>
        <Component {...pageProps} />
      </AuthProvider>
    </>
  );
}

export default MyApp;
